name: Docker Image CD

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code base
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . Dockerfile -t trusha2198/compose:v1
